//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartEducation
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassSchedule
    {
        public int CsId { get; set; }
        public int cId { get; set; }
        public string Day { get; set; }
    
        public virtual Cours Cours { get; set; }
        public virtual LectureSchedual LectureSchedual { get; set; }
    }
}
