//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartEducation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enroll
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Enroll()
        {
            this.Attendances = new HashSet<Attendance>();
        }
    
        public int eId { get; set; }
        public int StudentId { get; set; }
        public int cId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attendance> Attendances { get; set; }
        public virtual Cours Cours { get; set; }
        public virtual StudentInfo StudentInfo { get; set; }
    }
}
