//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartEducation
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentImage
    {
        public int ImageId { get; set; }
        public int StudentId { get; set; }
        public string ImageType { get; set; }
        public string ImagePath { get; set; }
        public System.DateTime ImageDate { get; set; }
    
        public virtual StudentInfo StudentInfo { get; set; }
    }
}
